### ISSUE TITLE
Request for arguments for different training stages

### ISSUE THREAD

**Issue by ayshrv** [HomeroRR/rmm#2]
Hi,

Thank you for the releasing the codebase.

I was trying to use this codebase and wanted to replicate the numbers provided in the paper. For me in order to accomplish that, could please provide the arguments that need to be passed to the training script for different stages of pretraining and finetuning for Navigator, Questioner and Guide?

Thanks!

**Comment by HomeroRR** [comment]
Hi Ayush,
I just updated the README.md with step-by-step instructions on how to run and reproduce the experiments. Also, it now includes pre-trained models.

Best,
Homero Roman Roman

**Comment by ayshrv** [comment]
Thanks for updating the README.
