### ISSUE TITLE
Time estimate to train RMM model

### ISSUE THREAD

**Issue by ayshrv** [HomeroRR/rmm#5]
Hi,

I wanted to know how much time does it take to train the RMM model. Basically, running this command:
```
python src/train.py --mode=gameplay --eval_branching=3 --action_probs_branching --train_datasets=CVDN --eval_datasets=CVDN
```

I had started this training and the log showed me that it would take 10 days (14883 m).

```
Bleu 1: 0.1260 Bleu 2: 0.0554, Bleu 3 :0.0195,  Bleu 4: 0.0055
2223m 57s (- 14883m 25s) (2600 13%) train loss: 0.6909, val_unseen loss: 0.7864, oracle success_rate: 0.047, dist_to_end_reduction: 4.479, oracle path_success_rate: 0.063, ceiling: 28.069, success_rate: 0.004, val_seen loss: 0.7294, oracle success_rate: 0.189, dist_to_end_reduction: 10.147, oracle path_success_rate: 0.200, ceiling: 31.571, success_rate: 0.089
EPOCH 2600
```

Do you think this is a reasonable estimate and did it take you the same amount of time?

For context, pretraining the agent only took me around 6 hours.

**Comment by ybisk** [comment]
Hi,

I believe these are all the training times Homero shared with me:
1. Pretraining 20K iterations: 4hrs, 33m 1056
2. baseline 5k iterations: 27hrs, 2min 1057
3. Data Aug 5k iterations: 19hrs, 21m 1058
4. RMM1 5k iterations: 70hrs, 5m 1059
5. RMM3 5k iterations: 109 hrs, 50m

This is based on a single NVIDIA P100 GPU

**Comment by ayshrv** [comment]
Thanks @ybisk !
