### ISSUE TITLE
Error when load the pre-trained model

### ISSUE THREAD

**Issue by Budding0828** [HomeroRR/rmm#6]
Hi, 
Thank you for sharing the source code, this is really a great job!  wow

I ran the code according to the readme you provided, and the following error occurred when reading the pre-trained model. Have you ever encountered a similar situation? It seems that the key value is wrong.

Traceback (most recent call last):
  File "src/train.py", line 572, in <module>
    train_val()
  File "src/train.py", line 568, in train_val
    train( train_env, agent, val_envs, tok)
  File "src/train.py", line 253, in train
    prev_iter = load(best_model, args.agent_pretrain_file)
  File "/public/cvdn-memcontext/src/utils.py", line 585, in load
    recover_state(*param)
  File "/public/cvdn-memcontext/src/utils.py", line 578, in recover_state
    model.load_state_dict(state)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EncoderLSTM:
        Unexpected key(s) in state_dict: "module.embedding.weight", "module.lstm.weight_ih_l0", "module.lstm.weight_hh_l0", "module.lstm.bias_ih_l0", "module.lstm.bias_hh_l0", "module.encoder2decoder.weight", "module.encoder2decoder.bias".

Looking forward to your reply!

**Comment by Budding0828** [comment]
Hi,
I may have found the problem.

```python
def load(best_model, path, with_critic=False, parallel=True):
    ''' Loads parameters (but not training state) '''
    states = torch.load(path)
    def recover_state(name, model, optimizer):
        state = model.state_dict()
        state.update(states[name]['state_dict'])
        # if parallel:
        #     new_state = {}
        #     for k, v in state.items():
        #         key = k[7:] if k[:7] == 'module.' else k# remove `module.`
        #         # print(key)
        #         new_state[key] = v
        #     state = new_state
        model.load_state_dict(state)
        optimizer.load_state_dict(states[name]['optimizer'])
    all_tuple = [("encoder", best_model['encoder'], best_model['encoder_optm']),
                    ("decoder", best_model['decoder'], best_model['decoder_optm'])]
    if with_critic:
        all_tuple.append(("critic", best_model['critic'], best_model['critic_optm']))
    for param in all_tuple:
        recover_state(*param)
    return states['encoder']['iteration']
```
This is the code from src/utils.py between Line 561 to LIne 582

The **states['encoder']['state_dict'].keys()** is as follow:
```
['module.embedding.weight', 'module.lstm.weight_ih_l0', 'module.lstm.weight_hh_l0', 'module.lstm.bias_ih_l0', 'module.lstm.bias_hh_l0', 'module.encoder2decoder.weight', 'module.encoder2decoder.bias']
```

while the **model.state_dict().keys()** is as follow:
```
['embedding.weight', 'lstm.weight_ih_l0', 'lstm.weight_hh_l0', 'lstm.bias_ih_l0', 'lstm.bias_hh_l0', 'encoder2decoder.weight', 'encoder2decoder.bias']
```

if do the ```state.update(states[name]['state_dict'])```, the **state.keys()** changes to:
```
['embedding.weight', 'lstm.weight_ih_l0', 'lstm.weight_hh_l0', 'lstm.bias_ih_l0', 'lstm.bias_hh_l0', 'encoder2decoder.weight', 'encoder2decoder.bias', 'module.embedding.weight', 'module.lstm.weight_ih_l0', 'module.lstm.weight_hh_l0', 'module.lstm.bias_ih_l0', 'module.lstm.bias_hh_l0', 'module.encoder2decoder.weight', 'module.encoder2decoder.bias']
```

which is unmatched to the **model.state()** and result to the error.

I would like to ask whether you have encountered similar problems before and if there is a better solution.

Thanks for your attention, looking forward to your reply !

**Comment by Budding0828** [comment]
Please forgive me, I am very interested in your model, and a lot of questions have arisen from it. lol 

I tried to solve the problem mentioned above, using the following method (through your comment code), I don't know if it is correct:
```python
def load(best_model, path, with_critic=False, parallel=True):
    ''' Loads parameters (but not training state) '''
    states = torch.load(path)
    def recover_state(name, model, optimizer):
        state = model.state_dict() 
        # add code
        # state.update(states[name]['state_dict'])
        new_state = {}
        for k, v in states[name]['state_dict'].items():
            k = k[7:] if k[:7] == 'module.' else k
            state[k] = v

        # if parallel:
        #     new_state = {}
        #     for k, v in state.items():
        #         key = k[7:] if k[:7] == 'module.' else k# remove `module.`
        #         # print(key)
        #         new_state[key] = v
        #     state = new_state

        model.load_state_dict(state)
        optimizer.load_state_dict(states[name]['optimizer'])
    all_tuple = [("encoder", best_model['encoder'], best_model['encoder_optm']),
                    ("decoder", best_model['decoder'], best_model['decoder_optm'])]
    if with_critic:
        all_tuple.append(("critic", best_model['critic'], best_model['critic_optm']))
    for param in all_tuple:
        recover_state(*param)
    return states['encoder']['iteration']
```

Through the above code, state can store the weight of the pre-trained model, but there are still problems with ```model.load_state_dict(state)```, this time the problem is related to the model.

```
Traceback (most recent call last):
  File "src/train.py", line 572, in <module>
    train_val()
  File "src/train.py", line 568, in train_val
    train( train_env, agent, val_envs, tok)
  File "src/train.py", line 253, in train
    prev_iter = load(best_model, args.agent_pretrain_file)
  File "/public/cvdn-memcontext/src/utils.py", line 593, in load
    recover_state(*param)
  File "/public/cvdn-memcontext/src/utils.py", line 586, in recover_state
    model.load_state_dict(state)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EncoderLSTM:
        size mismatch for embedding.weight: copying a param with shape torch.Size([1127, 256]) from checkpoint, the shape in current model is torch.Size([1201, 256]).
```

I tried to print the parameters of the **embedding layer** in the model, the scale is [1201, 256]. However, the scale of the loaded pre-training model parameters **state['encoder']['state_dict']['module.embedding.weight']** is [1127, 256].

Did I make a mistake in any link? Or is there a problem when uploading the pre-trained model?

Looking forward to your reply.

**Comment by HomeroRR** [comment]
Hi @Budding0828,
thank you for reporting the issue.
I already took a look into it and pushed fixes for your issues, please pull the latest version of the repo.

As you already figured out, the commented out code in the "if parallel" block removes the "module."
prefix from models that were saved in parallel
```# if parallel:
        #     new_state = {}
        #     for k, v in state.items():
        #         key = k[7:] if k[:7] == 'module.' else k# remove `module.`
        #         # print(key)
        #         new_state[key] = v
        #     state = new_state
```

As for the issue regarding 
``` copying a param with shape torch.Size([1127, 256]) ```
 it arises from a vocabulary size mismatch. I uploaded the train_vocab. txt and trainval_vocab.txt files to tasks/CVDN/data and set them as the defaults. 

Please let us know if you run into any more issues.

**Comment by Budding0828** [comment]
Hi, @HomeroRR 

Thank you for your detailed reply. Now the code can run successfully. I will continue to study, if there are new issues, I will contact you.

Heartfelt thanks.
